// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package Client.proto_client;

public final class Client {
  private Client() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SellOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto_client.Sell)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string usr = 1;</code>
     */
    boolean hasUsr();
    /**
     * <code>required string usr = 1;</code>
     */
    java.lang.String getUsr();
    /**
     * <code>required string usr = 1;</code>
     */
    com.google.protobuf.ByteString
        getUsrBytes();

    /**
     * <code>required string company = 2;</code>
     */
    boolean hasCompany();
    /**
     * <code>required string company = 2;</code>
     */
    java.lang.String getCompany();
    /**
     * <code>required string company = 2;</code>
     */
    com.google.protobuf.ByteString
        getCompanyBytes();

    /**
     * <code>required int32 actions = 3;</code>
     */
    boolean hasActions();
    /**
     * <code>required int32 actions = 3;</code>
     */
    int getActions();

    /**
     * <code>required float price = 4;</code>
     */
    boolean hasPrice();
    /**
     * <code>required float price = 4;</code>
     */
    float getPrice();
  }
  /**
   * Protobuf type {@code proto_client.Sell}
   */
  public  static final class Sell extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto_client.Sell)
      SellOrBuilder {
    // Use Sell.newBuilder() to construct.
    private Sell(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Sell() {
      usr_ = "";
      company_ = "";
      actions_ = 0;
      price_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Sell(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              usr_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              company_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              actions_ = input.readInt32();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              price_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto_client.Client.internal_static_proto_client_Sell_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto_client.Client.internal_static_proto_client_Sell_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto_client.Client.Sell.class, proto_client.Client.Sell.Builder.class);
    }

    private int bitField0_;
    public static final int USR_FIELD_NUMBER = 1;
    private volatile java.lang.Object usr_;
    /**
     * <code>required string usr = 1;</code>
     */
    public boolean hasUsr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string usr = 1;</code>
     */
    public java.lang.String getUsr() {
      java.lang.Object ref = usr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          usr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string usr = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsrBytes() {
      java.lang.Object ref = usr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        usr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPANY_FIELD_NUMBER = 2;
    private volatile java.lang.Object company_;
    /**
     * <code>required string company = 2;</code>
     */
    public boolean hasCompany() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string company = 2;</code>
     */
    public java.lang.String getCompany() {
      java.lang.Object ref = company_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          company_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string company = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCompanyBytes() {
      java.lang.Object ref = company_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        company_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTIONS_FIELD_NUMBER = 3;
    private int actions_;
    /**
     * <code>required int32 actions = 3;</code>
     */
    public boolean hasActions() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 actions = 3;</code>
     */
    public int getActions() {
      return actions_;
    }

    public static final int PRICE_FIELD_NUMBER = 4;
    private float price_;
    /**
     * <code>required float price = 4;</code>
     */
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required float price = 4;</code>
     */
    public float getPrice() {
      return price_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUsr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCompany()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasActions()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, usr_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, company_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, actions_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, price_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, usr_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, company_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, actions_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, price_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto_client.Client.Sell)) {
        return super.equals(obj);
      }
      proto_client.Client.Sell other = (proto_client.Client.Sell) obj;

      boolean result = true;
      result = result && (hasUsr() == other.hasUsr());
      if (hasUsr()) {
        result = result && getUsr()
            .equals(other.getUsr());
      }
      result = result && (hasCompany() == other.hasCompany());
      if (hasCompany()) {
        result = result && getCompany()
            .equals(other.getCompany());
      }
      result = result && (hasActions() == other.hasActions());
      if (hasActions()) {
        result = result && (getActions()
            == other.getActions());
      }
      result = result && (hasPrice() == other.hasPrice());
      if (hasPrice()) {
        result = result && (
            java.lang.Float.floatToIntBits(getPrice())
            == java.lang.Float.floatToIntBits(
                other.getPrice()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasUsr()) {
        hash = (37 * hash) + USR_FIELD_NUMBER;
        hash = (53 * hash) + getUsr().hashCode();
      }
      if (hasCompany()) {
        hash = (37 * hash) + COMPANY_FIELD_NUMBER;
        hash = (53 * hash) + getCompany().hashCode();
      }
      if (hasActions()) {
        hash = (37 * hash) + ACTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getActions();
      }
      if (hasPrice()) {
        hash = (37 * hash) + PRICE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getPrice());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto_client.Client.Sell parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_client.Client.Sell parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_client.Client.Sell parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_client.Client.Sell parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_client.Client.Sell parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_client.Client.Sell parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_client.Client.Sell parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto_client.Client.Sell parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_client.Client.Sell parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_client.Client.Sell parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto_client.Client.Sell prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto_client.Sell}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto_client.Sell)
        proto_client.Client.SellOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto_client.Client.internal_static_proto_client_Sell_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto_client.Client.internal_static_proto_client_Sell_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto_client.Client.Sell.class, proto_client.Client.Sell.Builder.class);
      }

      // Construct using proto_client.Client.Sell.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        usr_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        company_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        actions_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        price_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto_client.Client.internal_static_proto_client_Sell_descriptor;
      }

      public proto_client.Client.Sell getDefaultInstanceForType() {
        return proto_client.Client.Sell.getDefaultInstance();
      }

      public proto_client.Client.Sell build() {
        proto_client.Client.Sell result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto_client.Client.Sell buildPartial() {
        proto_client.Client.Sell result = new proto_client.Client.Sell(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.usr_ = usr_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.company_ = company_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.actions_ = actions_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.price_ = price_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto_client.Client.Sell) {
          return mergeFrom((proto_client.Client.Sell)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto_client.Client.Sell other) {
        if (other == proto_client.Client.Sell.getDefaultInstance()) return this;
        if (other.hasUsr()) {
          bitField0_ |= 0x00000001;
          usr_ = other.usr_;
          onChanged();
        }
        if (other.hasCompany()) {
          bitField0_ |= 0x00000002;
          company_ = other.company_;
          onChanged();
        }
        if (other.hasActions()) {
          setActions(other.getActions());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUsr()) {
          return false;
        }
        if (!hasCompany()) {
          return false;
        }
        if (!hasActions()) {
          return false;
        }
        if (!hasPrice()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto_client.Client.Sell parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto_client.Client.Sell) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object usr_ = "";
      /**
       * <code>required string usr = 1;</code>
       */
      public boolean hasUsr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string usr = 1;</code>
       */
      public java.lang.String getUsr() {
        java.lang.Object ref = usr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            usr_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string usr = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUsrBytes() {
        java.lang.Object ref = usr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          usr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string usr = 1;</code>
       */
      public Builder setUsr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        usr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string usr = 1;</code>
       */
      public Builder clearUsr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        usr_ = getDefaultInstance().getUsr();
        onChanged();
        return this;
      }
      /**
       * <code>required string usr = 1;</code>
       */
      public Builder setUsrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        usr_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object company_ = "";
      /**
       * <code>required string company = 2;</code>
       */
      public boolean hasCompany() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string company = 2;</code>
       */
      public java.lang.String getCompany() {
        java.lang.Object ref = company_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            company_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string company = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCompanyBytes() {
        java.lang.Object ref = company_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          company_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string company = 2;</code>
       */
      public Builder setCompany(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        company_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string company = 2;</code>
       */
      public Builder clearCompany() {
        bitField0_ = (bitField0_ & ~0x00000002);
        company_ = getDefaultInstance().getCompany();
        onChanged();
        return this;
      }
      /**
       * <code>required string company = 2;</code>
       */
      public Builder setCompanyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        company_ = value;
        onChanged();
        return this;
      }

      private int actions_ ;
      /**
       * <code>required int32 actions = 3;</code>
       */
      public boolean hasActions() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 actions = 3;</code>
       */
      public int getActions() {
        return actions_;
      }
      /**
       * <code>required int32 actions = 3;</code>
       */
      public Builder setActions(int value) {
        bitField0_ |= 0x00000004;
        actions_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 actions = 3;</code>
       */
      public Builder clearActions() {
        bitField0_ = (bitField0_ & ~0x00000004);
        actions_ = 0;
        onChanged();
        return this;
      }

      private float price_ ;
      /**
       * <code>required float price = 4;</code>
       */
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required float price = 4;</code>
       */
      public float getPrice() {
        return price_;
      }
      /**
       * <code>required float price = 4;</code>
       */
      public Builder setPrice(float value) {
        bitField0_ |= 0x00000008;
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float price = 4;</code>
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000008);
        price_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto_client.Sell)
    }

    // @@protoc_insertion_point(class_scope:proto_client.Sell)
    private static final proto_client.Client.Sell DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto_client.Client.Sell();
    }

    public static proto_client.Client.Sell getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Sell>
        PARSER = new com.google.protobuf.AbstractParser<Sell>() {
      public Sell parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Sell(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Sell> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Sell> getParserForType() {
      return PARSER;
    }

    public proto_client.Client.Sell getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BuyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto_client.Buy)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string usr = 1;</code>
     */
    boolean hasUsr();
    /**
     * <code>required string usr = 1;</code>
     */
    java.lang.String getUsr();
    /**
     * <code>required string usr = 1;</code>
     */
    com.google.protobuf.ByteString
        getUsrBytes();

    /**
     * <code>required string company = 2;</code>
     */
    boolean hasCompany();
    /**
     * <code>required string company = 2;</code>
     */
    java.lang.String getCompany();
    /**
     * <code>required string company = 2;</code>
     */
    com.google.protobuf.ByteString
        getCompanyBytes();

    /**
     * <code>required int32 actions = 3;</code>
     */
    boolean hasActions();
    /**
     * <code>required int32 actions = 3;</code>
     */
    int getActions();

    /**
     * <code>required float price = 4;</code>
     */
    boolean hasPrice();
    /**
     * <code>required float price = 4;</code>
     */
    float getPrice();
  }
  /**
   * Protobuf type {@code proto_client.Buy}
   */
  public  static final class Buy extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto_client.Buy)
      BuyOrBuilder {
    // Use Buy.newBuilder() to construct.
    private Buy(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Buy() {
      usr_ = "";
      company_ = "";
      actions_ = 0;
      price_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Buy(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              usr_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              company_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              actions_ = input.readInt32();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              price_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto_client.Client.internal_static_proto_client_Buy_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto_client.Client.internal_static_proto_client_Buy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto_client.Client.Buy.class, proto_client.Client.Buy.Builder.class);
    }

    private int bitField0_;
    public static final int USR_FIELD_NUMBER = 1;
    private volatile java.lang.Object usr_;
    /**
     * <code>required string usr = 1;</code>
     */
    public boolean hasUsr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string usr = 1;</code>
     */
    public java.lang.String getUsr() {
      java.lang.Object ref = usr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          usr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string usr = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsrBytes() {
      java.lang.Object ref = usr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        usr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPANY_FIELD_NUMBER = 2;
    private volatile java.lang.Object company_;
    /**
     * <code>required string company = 2;</code>
     */
    public boolean hasCompany() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string company = 2;</code>
     */
    public java.lang.String getCompany() {
      java.lang.Object ref = company_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          company_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string company = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCompanyBytes() {
      java.lang.Object ref = company_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        company_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTIONS_FIELD_NUMBER = 3;
    private int actions_;
    /**
     * <code>required int32 actions = 3;</code>
     */
    public boolean hasActions() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 actions = 3;</code>
     */
    public int getActions() {
      return actions_;
    }

    public static final int PRICE_FIELD_NUMBER = 4;
    private float price_;
    /**
     * <code>required float price = 4;</code>
     */
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required float price = 4;</code>
     */
    public float getPrice() {
      return price_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUsr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCompany()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasActions()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, usr_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, company_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, actions_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, price_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, usr_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, company_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, actions_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, price_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto_client.Client.Buy)) {
        return super.equals(obj);
      }
      proto_client.Client.Buy other = (proto_client.Client.Buy) obj;

      boolean result = true;
      result = result && (hasUsr() == other.hasUsr());
      if (hasUsr()) {
        result = result && getUsr()
            .equals(other.getUsr());
      }
      result = result && (hasCompany() == other.hasCompany());
      if (hasCompany()) {
        result = result && getCompany()
            .equals(other.getCompany());
      }
      result = result && (hasActions() == other.hasActions());
      if (hasActions()) {
        result = result && (getActions()
            == other.getActions());
      }
      result = result && (hasPrice() == other.hasPrice());
      if (hasPrice()) {
        result = result && (
            java.lang.Float.floatToIntBits(getPrice())
            == java.lang.Float.floatToIntBits(
                other.getPrice()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasUsr()) {
        hash = (37 * hash) + USR_FIELD_NUMBER;
        hash = (53 * hash) + getUsr().hashCode();
      }
      if (hasCompany()) {
        hash = (37 * hash) + COMPANY_FIELD_NUMBER;
        hash = (53 * hash) + getCompany().hashCode();
      }
      if (hasActions()) {
        hash = (37 * hash) + ACTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getActions();
      }
      if (hasPrice()) {
        hash = (37 * hash) + PRICE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getPrice());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto_client.Client.Buy parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_client.Client.Buy parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_client.Client.Buy parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_client.Client.Buy parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_client.Client.Buy parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_client.Client.Buy parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_client.Client.Buy parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto_client.Client.Buy parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_client.Client.Buy parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_client.Client.Buy parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto_client.Client.Buy prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto_client.Buy}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto_client.Buy)
        proto_client.Client.BuyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto_client.Client.internal_static_proto_client_Buy_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto_client.Client.internal_static_proto_client_Buy_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto_client.Client.Buy.class, proto_client.Client.Buy.Builder.class);
      }

      // Construct using proto_client.Client.Buy.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        usr_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        company_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        actions_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        price_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto_client.Client.internal_static_proto_client_Buy_descriptor;
      }

      public proto_client.Client.Buy getDefaultInstanceForType() {
        return proto_client.Client.Buy.getDefaultInstance();
      }

      public proto_client.Client.Buy build() {
        proto_client.Client.Buy result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto_client.Client.Buy buildPartial() {
        proto_client.Client.Buy result = new proto_client.Client.Buy(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.usr_ = usr_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.company_ = company_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.actions_ = actions_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.price_ = price_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto_client.Client.Buy) {
          return mergeFrom((proto_client.Client.Buy)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto_client.Client.Buy other) {
        if (other == proto_client.Client.Buy.getDefaultInstance()) return this;
        if (other.hasUsr()) {
          bitField0_ |= 0x00000001;
          usr_ = other.usr_;
          onChanged();
        }
        if (other.hasCompany()) {
          bitField0_ |= 0x00000002;
          company_ = other.company_;
          onChanged();
        }
        if (other.hasActions()) {
          setActions(other.getActions());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUsr()) {
          return false;
        }
        if (!hasCompany()) {
          return false;
        }
        if (!hasActions()) {
          return false;
        }
        if (!hasPrice()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto_client.Client.Buy parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto_client.Client.Buy) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object usr_ = "";
      /**
       * <code>required string usr = 1;</code>
       */
      public boolean hasUsr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string usr = 1;</code>
       */
      public java.lang.String getUsr() {
        java.lang.Object ref = usr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            usr_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string usr = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUsrBytes() {
        java.lang.Object ref = usr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          usr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string usr = 1;</code>
       */
      public Builder setUsr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        usr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string usr = 1;</code>
       */
      public Builder clearUsr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        usr_ = getDefaultInstance().getUsr();
        onChanged();
        return this;
      }
      /**
       * <code>required string usr = 1;</code>
       */
      public Builder setUsrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        usr_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object company_ = "";
      /**
       * <code>required string company = 2;</code>
       */
      public boolean hasCompany() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string company = 2;</code>
       */
      public java.lang.String getCompany() {
        java.lang.Object ref = company_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            company_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string company = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCompanyBytes() {
        java.lang.Object ref = company_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          company_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string company = 2;</code>
       */
      public Builder setCompany(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        company_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string company = 2;</code>
       */
      public Builder clearCompany() {
        bitField0_ = (bitField0_ & ~0x00000002);
        company_ = getDefaultInstance().getCompany();
        onChanged();
        return this;
      }
      /**
       * <code>required string company = 2;</code>
       */
      public Builder setCompanyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        company_ = value;
        onChanged();
        return this;
      }

      private int actions_ ;
      /**
       * <code>required int32 actions = 3;</code>
       */
      public boolean hasActions() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 actions = 3;</code>
       */
      public int getActions() {
        return actions_;
      }
      /**
       * <code>required int32 actions = 3;</code>
       */
      public Builder setActions(int value) {
        bitField0_ |= 0x00000004;
        actions_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 actions = 3;</code>
       */
      public Builder clearActions() {
        bitField0_ = (bitField0_ & ~0x00000004);
        actions_ = 0;
        onChanged();
        return this;
      }

      private float price_ ;
      /**
       * <code>required float price = 4;</code>
       */
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required float price = 4;</code>
       */
      public float getPrice() {
        return price_;
      }
      /**
       * <code>required float price = 4;</code>
       */
      public Builder setPrice(float value) {
        bitField0_ |= 0x00000008;
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float price = 4;</code>
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000008);
        price_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto_client.Buy)
    }

    // @@protoc_insertion_point(class_scope:proto_client.Buy)
    private static final proto_client.Client.Buy DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto_client.Client.Buy();
    }

    public static proto_client.Client.Buy getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Buy>
        PARSER = new com.google.protobuf.AbstractParser<Buy>() {
      public Buy parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Buy(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Buy> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Buy> getParserForType() {
      return PARSER;
    }

    public proto_client.Client.Buy getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_client_Sell_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_client_Sell_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_client_Buy_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_client_Buy_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014client.proto\022\014proto_client\"D\n\004Sell\022\013\n\003" +
      "usr\030\001 \002(\t\022\017\n\007company\030\002 \002(\t\022\017\n\007actions\030\003 " +
      "\002(\005\022\r\n\005price\030\004 \002(\002\"C\n\003Buy\022\013\n\003usr\030\001 \002(\t\022\017" +
      "\n\007company\030\002 \002(\t\022\017\n\007actions\030\003 \002(\005\022\r\n\005pric" +
      "e\030\004 \002(\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_client_Sell_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_client_Sell_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_client_Sell_descriptor,
        new java.lang.String[] { "Usr", "Company", "Actions", "Price", });
    internal_static_proto_client_Buy_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_client_Buy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_client_Buy_descriptor,
        new java.lang.String[] { "Usr", "Company", "Actions", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
